export const categoryList = {
  main: 'Основні страви',
  meat: "М'ясні страви",
  fish: 'Рибні страви',
  vegetable: 'Овочеві страви',
  porridge: 'Каші',
  sides: 'Гарніри',
  soups: 'Супи',
  salads: 'Салати',
  breakfast: 'Сніданки',
  snacks: 'Закуски',
  desserts: 'Десерти',
  baking: 'Випічка',
  drinks: 'Напої',
  sauces: 'Соуси',
  preserves: 'Консервація',
  vegetarian: 'Вегетаріанські страви',
  lean: 'Пісні страви',
  glutenfree: 'Безглютенові',
  grill: 'Гриль / мангал',
  other: 'Інше',
} as const
